name: Reactjs Docker Deploy

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing

    steps:
      # Step 1: Check out code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 7: Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:latest .
          docker tag ${{ secrets.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          echo "Docker image built and tagged successfully."

      # Step 9: Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          echo "Pushing Docker image to DockerHub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest
          echo "Docker image pushed to DockerHub successfully."
    